language: ruby
rvm:
- '2.3.1'
sudo: false
cache:
  bundler: true
  directories:
    - vendor/assets/bower_components
before_cache:
- cat bower.json > vendor/assets/bower_components/bower.json
env:
  global:
  - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=300000
  - RUBY_GC_HEAP_INIT_SLOTS=600000
  - RUBY_GC_HEAP_GROWTH_FACTOR=1.25
  # https://coveralls.zendesk.com/hc/en-us/articles/203484329-Parallel-Build-Webhook
  # TODO: notification to make Coveralls combine the partial uploads
  - COVERALLS_PARALLEL=true
  # https://github.com/grosser/parallel_tests/wiki/Distributed-Parallel-Tests-and-Travis-Support
  - PARALLEL_TEST_PROCESSORS=4
  matrix:
  - TEST_SUITE=vmdb PARALLEL=true TEST_GROUPS=1,2
  - TEST_SUITE=vmdb PARALLEL=true TEST_GROUPS=3,4
  - TEST_SUITE=migrations
  - TEST_SUITE=brakeman
matrix:
  fast_finish: true
addons:
  postgresql: '9.4'
before_install:
- source ${TRAVIS_BUILD_DIR}/tools/ci/before_install.sh
before_script:
- bundle exec rake test:$TEST_SUITE:setup
script:
- bundle exec rake test:$TEST_SUITE
after_failure:
- source ${TRAVIS_BUILD_DIR}/tools/ci/after_failure.sh
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7af45001fe6b7a4039f2
    on_success: change
    on_failure: always
    on_start: never
